# Generated by Django 2.2.16 on 2020-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
