# Generated by Django 2.2.16 on 2020-09-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='project',
        ),
        migrations.AddField(
            model_name='customtext',
            name='projectname',
            field=models.ManyToManyField(blank=True, related_name='customtext_projectname', to='home.Fuel'),
        ),
    ]
